# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='column2.proto',
  package='',
  serialized_pb='\n\rcolumn2.proto\"\xb6\x01\n\x0c\x44\x61taMessage2\x12 \n\x04type\x18\x01 \x02(\x0e\x32\x12.DataMessage2.Type\x12\x12\n\noperatorID\x18\x02 \x01(\x04\x12 \n\x07\x63olumns\x18\x03 \x03(\x0b\x32\x0f.ColumnMessage2\x12\x12\n\nnum_tuples\x18\x04 \x01(\r\x12\x0b\n\x03seq\x18\x05 \x01(\x04\"-\n\x04Type\x12\x07\n\x03\x45OS\x10\x00\x12\n\n\x06NORMAL\x10\x01\x12\x07\n\x03\x45OI\x10\x02\x12\x07\n\x03\x42OS\x10\x03\"\x89\x03\n\x0e\x43olumnMessage2\x12\"\n\x04type\x18\x01 \x02(\x0e\x32\x14.ColumnMessage2.Type\x12&\n\nint_column\x18\x03 \x01(\x0b\x32\x12.IntColumnMessage2\x12(\n\x0blong_column\x18\x04 \x01(\x0b\x32\x13.LongColumnMessage2\x12*\n\x0c\x66loat_column\x18\x05 \x01(\x0b\x32\x14.FloatColumnMessage2\x12,\n\rdouble_column\x18\x06 \x01(\x0b\x32\x15.DoubleColumnMessage2\x12,\n\rstring_column\x18\x07 \x01(\x0b\x32\x15.StringColumnMessage2\x12.\n\x0e\x62oolean_column\x18\x08 \x01(\x0b\x32\x16.BooleanColumnMessage2\"I\n\x04Type\x12\x07\n\x03INT\x10\x00\x12\x08\n\x04LONG\x10\x01\x12\t\n\x05\x46LOAT\x10\x02\x12\n\n\x06\x44OUBLE\x10\x03\x12\n\n\x06STRING\x10\x04\x12\x0b\n\x07\x42OOLEAN\x10\x05\"%\n\x11IntColumnMessage2\x12\x10\n\x04\x64\x61ta\x18\x01 \x03(\x05\x42\x02\x10\x01\"\"\n\x12LongColumnMessage2\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x12\"#\n\x13\x46loatColumnMessage2\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\"$\n\x14\x44oubleColumnMessage2\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\"X\n\x14StringColumnMessage2\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x0c\x12\x19\n\rstart_indices\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\x17\n\x0b\x65nd_indices\x18\x03 \x03(\x05\x42\x02\x10\x01\"%\n\x15\x42ooleanColumnMessage2\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\x42\x32\n$edu.washington.escience.myriad.protoB\nDataProto2')



_DATAMESSAGE2_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='DataMessage2.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='EOS', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NORMAL', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EOI', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BOS', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=155,
  serialized_end=200,
)

_COLUMNMESSAGE2_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='ColumnMessage2.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='INT', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LONG', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FLOAT', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DOUBLE', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STRING', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BOOLEAN', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=523,
  serialized_end=596,
)


_DATAMESSAGE2 = descriptor.Descriptor(
  name='DataMessage2',
  full_name='DataMessage2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='DataMessage2.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='operatorID', full_name='DataMessage2.operatorID', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='columns', full_name='DataMessage2.columns', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_tuples', full_name='DataMessage2.num_tuples', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='seq', full_name='DataMessage2.seq', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DATAMESSAGE2_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=200,
)


_COLUMNMESSAGE2 = descriptor.Descriptor(
  name='ColumnMessage2',
  full_name='ColumnMessage2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='ColumnMessage2.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='int_column', full_name='ColumnMessage2.int_column', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='long_column', full_name='ColumnMessage2.long_column', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='float_column', full_name='ColumnMessage2.float_column', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='double_column', full_name='ColumnMessage2.double_column', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='string_column', full_name='ColumnMessage2.string_column', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='boolean_column', full_name='ColumnMessage2.boolean_column', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COLUMNMESSAGE2_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=203,
  serialized_end=596,
)


_INTCOLUMNMESSAGE2 = descriptor.Descriptor(
  name='IntColumnMessage2',
  full_name='IntColumnMessage2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='IntColumnMessage2.data', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=598,
  serialized_end=635,
)


_LONGCOLUMNMESSAGE2 = descriptor.Descriptor(
  name='LongColumnMessage2',
  full_name='LongColumnMessage2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='LongColumnMessage2.data', index=0,
      number=1, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=637,
  serialized_end=671,
)


_FLOATCOLUMNMESSAGE2 = descriptor.Descriptor(
  name='FloatColumnMessage2',
  full_name='FloatColumnMessage2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='FloatColumnMessage2.data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=673,
  serialized_end=708,
)


_DOUBLECOLUMNMESSAGE2 = descriptor.Descriptor(
  name='DoubleColumnMessage2',
  full_name='DoubleColumnMessage2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='DoubleColumnMessage2.data', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=710,
  serialized_end=746,
)


_STRINGCOLUMNMESSAGE2 = descriptor.Descriptor(
  name='StringColumnMessage2',
  full_name='StringColumnMessage2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='StringColumnMessage2.data', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='start_indices', full_name='StringColumnMessage2.start_indices', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    descriptor.FieldDescriptor(
      name='end_indices', full_name='StringColumnMessage2.end_indices', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=748,
  serialized_end=836,
)


_BOOLEANCOLUMNMESSAGE2 = descriptor.Descriptor(
  name='BooleanColumnMessage2',
  full_name='BooleanColumnMessage2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='BooleanColumnMessage2.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=838,
  serialized_end=875,
)

_DATAMESSAGE2.fields_by_name['type'].enum_type = _DATAMESSAGE2_TYPE
_DATAMESSAGE2.fields_by_name['columns'].message_type = _COLUMNMESSAGE2
_DATAMESSAGE2_TYPE.containing_type = _DATAMESSAGE2;
_COLUMNMESSAGE2.fields_by_name['type'].enum_type = _COLUMNMESSAGE2_TYPE
_COLUMNMESSAGE2.fields_by_name['int_column'].message_type = _INTCOLUMNMESSAGE2
_COLUMNMESSAGE2.fields_by_name['long_column'].message_type = _LONGCOLUMNMESSAGE2
_COLUMNMESSAGE2.fields_by_name['float_column'].message_type = _FLOATCOLUMNMESSAGE2
_COLUMNMESSAGE2.fields_by_name['double_column'].message_type = _DOUBLECOLUMNMESSAGE2
_COLUMNMESSAGE2.fields_by_name['string_column'].message_type = _STRINGCOLUMNMESSAGE2
_COLUMNMESSAGE2.fields_by_name['boolean_column'].message_type = _BOOLEANCOLUMNMESSAGE2
_COLUMNMESSAGE2_TYPE.containing_type = _COLUMNMESSAGE2;
DESCRIPTOR.message_types_by_name['DataMessage2'] = _DATAMESSAGE2
DESCRIPTOR.message_types_by_name['ColumnMessage2'] = _COLUMNMESSAGE2
DESCRIPTOR.message_types_by_name['IntColumnMessage2'] = _INTCOLUMNMESSAGE2
DESCRIPTOR.message_types_by_name['LongColumnMessage2'] = _LONGCOLUMNMESSAGE2
DESCRIPTOR.message_types_by_name['FloatColumnMessage2'] = _FLOATCOLUMNMESSAGE2
DESCRIPTOR.message_types_by_name['DoubleColumnMessage2'] = _DOUBLECOLUMNMESSAGE2
DESCRIPTOR.message_types_by_name['StringColumnMessage2'] = _STRINGCOLUMNMESSAGE2
DESCRIPTOR.message_types_by_name['BooleanColumnMessage2'] = _BOOLEANCOLUMNMESSAGE2

class DataMessage2(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DATAMESSAGE2
  
  # @@protoc_insertion_point(class_scope:DataMessage2)

class ColumnMessage2(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COLUMNMESSAGE2
  
  # @@protoc_insertion_point(class_scope:ColumnMessage2)

class IntColumnMessage2(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INTCOLUMNMESSAGE2
  
  # @@protoc_insertion_point(class_scope:IntColumnMessage2)

class LongColumnMessage2(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LONGCOLUMNMESSAGE2
  
  # @@protoc_insertion_point(class_scope:LongColumnMessage2)

class FloatColumnMessage2(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FLOATCOLUMNMESSAGE2
  
  # @@protoc_insertion_point(class_scope:FloatColumnMessage2)

class DoubleColumnMessage2(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOUBLECOLUMNMESSAGE2
  
  # @@protoc_insertion_point(class_scope:DoubleColumnMessage2)

class StringColumnMessage2(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRINGCOLUMNMESSAGE2
  
  # @@protoc_insertion_point(class_scope:StringColumnMessage2)

class BooleanColumnMessage2(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOOLEANCOLUMNMESSAGE2
  
  # @@protoc_insertion_point(class_scope:BooleanColumnMessage2)

# @@protoc_insertion_point(module_scope)
