# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import column_pb2
import control_pb2
import query_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='main.proto',
  package='',
  serialized_pb='\n\nmain.proto\x1a\x0c\x63olumn.proto\x1a\rcontrol.proto\x1a\x0bquery.proto\"\xd3\x01\n\x10TransportMessage\x12$\n\x04type\x18\x01 \x02(\x0e\x32\x16.TransportMessage.Type\x12!\n\x0b\x64\x61taMessage\x18\x02 \x01(\x0b\x32\x0c.DataMessage\x12#\n\x0cqueryMessage\x18\x03 \x01(\x0b\x32\r.QueryMessage\x12\'\n\x0e\x63ontrolMessage\x18\x04 \x01(\x0b\x32\x0f.ControlMessage\"(\n\x04Type\x12\x08\n\x04\x44\x41TA\x10\x00\x12\t\n\x05QUERY\x10\x01\x12\x0b\n\x07\x43ONTROL\x10\x02\x42\x36\n$edu.washington.escience.myriad.protoB\x0eTransportProto')



_TRANSPORTMESSAGE_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='TransportMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='DATA', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='QUERY', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONTROL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=228,
  serialized_end=268,
)


_TRANSPORTMESSAGE = descriptor.Descriptor(
  name='TransportMessage',
  full_name='TransportMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='TransportMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dataMessage', full_name='TransportMessage.dataMessage', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='queryMessage', full_name='TransportMessage.queryMessage', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='controlMessage', full_name='TransportMessage.controlMessage', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRANSPORTMESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=57,
  serialized_end=268,
)

_TRANSPORTMESSAGE.fields_by_name['type'].enum_type = _TRANSPORTMESSAGE_TYPE
_TRANSPORTMESSAGE.fields_by_name['dataMessage'].message_type = column_pb2._DATAMESSAGE
_TRANSPORTMESSAGE.fields_by_name['queryMessage'].message_type = query_pb2._QUERYMESSAGE
_TRANSPORTMESSAGE.fields_by_name['controlMessage'].message_type = control_pb2._CONTROLMESSAGE
_TRANSPORTMESSAGE_TYPE.containing_type = _TRANSPORTMESSAGE;
DESCRIPTOR.message_types_by_name['TransportMessage'] = _TRANSPORTMESSAGE

class TransportMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRANSPORTMESSAGE
  
  # @@protoc_insertion_point(class_scope:TransportMessage)

# @@protoc_insertion_point(module_scope)
