// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

package edu.washington.escience.myriad.proto;

public final class ControlProto {
  private ControlProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ControlMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .ControlMessage.Type type = 1;
    boolean hasType();
    edu.washington.escience.myriad.proto.ControlProto.ControlMessage.Type getType();
  }
  public static final class ControlMessage extends
      com.google.protobuf.GeneratedMessage
      implements ControlMessageOrBuilder {
    // Use ControlMessage.newBuilder() to construct.
    private ControlMessage(Builder builder) {
      super(builder);
    }
    private ControlMessage(boolean noInit) {}
    
    private static final ControlMessage defaultInstance;
    public static ControlMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ControlMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.washington.escience.myriad.proto.ControlProto.internal_static_ControlMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.washington.escience.myriad.proto.ControlProto.internal_static_ControlMessage_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      SHUTDOWN(0, 3),
      WORKER_HEARTBEAT(1, 5),
      ;
      
      public static final int SHUTDOWN_VALUE = 3;
      public static final int WORKER_HEARTBEAT_VALUE = 5;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 3: return SHUTDOWN;
          case 5: return WORKER_HEARTBEAT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.washington.escience.myriad.proto.ControlProto.ControlMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        SHUTDOWN, WORKER_HEARTBEAT, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:ControlMessage.Type)
    }
    
    private int bitField0_;
    // required .ControlMessage.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private edu.washington.escience.myriad.proto.ControlProto.ControlMessage.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public edu.washington.escience.myriad.proto.ControlProto.ControlMessage.Type getType() {
      return type_;
    }
    
    private void initFields() {
      type_ = edu.washington.escience.myriad.proto.ControlProto.ControlMessage.Type.SHUTDOWN;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.washington.escience.myriad.proto.ControlProto.ControlMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.washington.escience.myriad.proto.ControlProto.ControlMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.washington.escience.myriad.proto.ControlProto.ControlMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.washington.escience.myriad.proto.ControlProto.ControlMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.washington.escience.myriad.proto.ControlProto.ControlMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.washington.escience.myriad.proto.ControlProto.ControlMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.washington.escience.myriad.proto.ControlProto.ControlMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.washington.escience.myriad.proto.ControlProto.ControlMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.washington.escience.myriad.proto.ControlProto.ControlMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.washington.escience.myriad.proto.ControlProto.ControlMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.washington.escience.myriad.proto.ControlProto.ControlMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.washington.escience.myriad.proto.ControlProto.ControlMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.washington.escience.myriad.proto.ControlProto.internal_static_ControlMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.washington.escience.myriad.proto.ControlProto.internal_static_ControlMessage_fieldAccessorTable;
      }
      
      // Construct using edu.washington.escience.myriad.proto.ControlProto.ControlMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = edu.washington.escience.myriad.proto.ControlProto.ControlMessage.Type.SHUTDOWN;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.washington.escience.myriad.proto.ControlProto.ControlMessage.getDescriptor();
      }
      
      public edu.washington.escience.myriad.proto.ControlProto.ControlMessage getDefaultInstanceForType() {
        return edu.washington.escience.myriad.proto.ControlProto.ControlMessage.getDefaultInstance();
      }
      
      public edu.washington.escience.myriad.proto.ControlProto.ControlMessage build() {
        edu.washington.escience.myriad.proto.ControlProto.ControlMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.washington.escience.myriad.proto.ControlProto.ControlMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.washington.escience.myriad.proto.ControlProto.ControlMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.washington.escience.myriad.proto.ControlProto.ControlMessage buildPartial() {
        edu.washington.escience.myriad.proto.ControlProto.ControlMessage result = new edu.washington.escience.myriad.proto.ControlProto.ControlMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.washington.escience.myriad.proto.ControlProto.ControlMessage) {
          return mergeFrom((edu.washington.escience.myriad.proto.ControlProto.ControlMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.washington.escience.myriad.proto.ControlProto.ControlMessage other) {
        if (other == edu.washington.escience.myriad.proto.ControlProto.ControlMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.washington.escience.myriad.proto.ControlProto.ControlMessage.Type value = edu.washington.escience.myriad.proto.ControlProto.ControlMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .ControlMessage.Type type = 1;
      private edu.washington.escience.myriad.proto.ControlProto.ControlMessage.Type type_ = edu.washington.escience.myriad.proto.ControlProto.ControlMessage.Type.SHUTDOWN;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public edu.washington.escience.myriad.proto.ControlProto.ControlMessage.Type getType() {
        return type_;
      }
      public Builder setType(edu.washington.escience.myriad.proto.ControlProto.ControlMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = edu.washington.escience.myriad.proto.ControlProto.ControlMessage.Type.SHUTDOWN;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ControlMessage)
    }
    
    static {
      defaultInstance = new ControlMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ControlMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ControlMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ControlMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcontrol.proto\"`\n\016ControlMessage\022\"\n\004typ" +
      "e\030\001 \002(\0162\024.ControlMessage.Type\"*\n\004Type\022\014\n" +
      "\010SHUTDOWN\020\003\022\024\n\020WORKER_HEARTBEAT\020\005B4\n$edu" +
      ".washington.escience.myriad.protoB\014Contr" +
      "olProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ControlMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ControlMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ControlMessage_descriptor,
              new java.lang.String[] { "Type", },
              edu.washington.escience.myriad.proto.ControlProto.ControlMessage.class,
              edu.washington.escience.myriad.proto.ControlProto.ControlMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
