package edu.washington.escience.myria.parallel;

import edu.washington.escience.myria.DbException;
import edu.washington.escience.myria.TupleBatch;
import edu.washington.escience.myria.TupleBatchBuffer;
import edu.washington.escience.myria.operator.Operator;

/**
 * The producer part of the Collect Exchange operator.
 * 
 * The producer actively pushes the tuples generated by the child operator to the paired CollectConsumer.
 * 
 */
public final class CollectProducer extends Producer {

  /** Required for Java serialization. */
  private static final long serialVersionUID = 1L;

  /**
   * @param child the child who provides data for this producer to distribute.
   * @param operatorID destination operator the data goes
   * @param collectConsumerWorkerID destination worker the data goes.
   * */
  public CollectProducer(final Operator child, final ExchangePairID operatorID, final int collectConsumerWorkerID) {
    super(child, operatorID, collectConsumerWorkerID);
  }

  @Override
  protected void consumeTuples(final TupleBatch tb) throws DbException {
    TupleBatch dm = null;
    tb.compactInto(getBuffers()[0]);
    while ((dm = getBuffers()[0].popAnyUsingTimeout()) != null) {
      try {
        writeMessage(0, dm, getBuffers()[0]);
      } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
        return;
      }
    }
  }

  @Override
  protected void childEOS() throws DbException {
    TupleBatch dm = null;
    while ((dm = getBuffers()[0].popAny()) != null) {
      try {
        writeMessage(0, dm, getBuffers()[0]);
      } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
        return;
      }
    }
    super.channelEnds(0);
  }

  @Override
  protected void childEOI() throws DbException {
    TupleBatch dm = null;
    TupleBatchBuffer tbb = getBuffers()[0];
    TupleBatch.eoiTupleBatch(getSchema()).compactInto(tbb);
    while ((dm = tbb.popAny()) != null) {
      try {
        writeMessage(0, dm, getBuffers()[0]);
      } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
        return;
      }
    }
  }
}
