// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: export.proto

package edu.washington.escience.myria.proto;

public final class Graph {
  private Graph() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VertexOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required double value = 2;
    /**
     * <code>required double value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required double value = 2;</code>
     */
    double getValue();

    // repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
     */
    java.util.List<edu.washington.escience.myria.proto.Graph.Vertex.Edge> 
        getEdgeList();
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
     */
    edu.washington.escience.myria.proto.Graph.Vertex.Edge getEdge(int index);
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
     */
    int getEdgeCount();
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
     */
    java.util.List<? extends edu.washington.escience.myria.proto.Graph.Vertex.EdgeOrBuilder> 
        getEdgeOrBuilderList();
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
     */
    edu.washington.escience.myria.proto.Graph.Vertex.EdgeOrBuilder getEdgeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code edu.washington.escience.myria.proto.Vertex}
   */
  public static final class Vertex extends
      com.google.protobuf.GeneratedMessage
      implements VertexOrBuilder {
    // Use Vertex.newBuilder() to construct.
    private Vertex(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Vertex(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Vertex defaultInstance;
    public static Vertex getDefaultInstance() {
      return defaultInstance;
    }

    public Vertex getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Vertex(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              value_ = input.readDouble();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                edge_ = new java.util.ArrayList<edu.washington.escience.myria.proto.Graph.Vertex.Edge>();
                mutable_bitField0_ |= 0x00000004;
              }
              edge_.add(input.readMessage(edu.washington.escience.myria.proto.Graph.Vertex.Edge.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          edge_ = java.util.Collections.unmodifiableList(edge_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertex_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertex_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.washington.escience.myria.proto.Graph.Vertex.class, edu.washington.escience.myria.proto.Graph.Vertex.Builder.class);
    }

    public static com.google.protobuf.Parser<Vertex> PARSER =
        new com.google.protobuf.AbstractParser<Vertex>() {
      public Vertex parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vertex(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Vertex> getParserForType() {
      return PARSER;
    }

    public interface EdgeOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 destination_id = 3;
      /**
       * <code>required int32 destination_id = 3;</code>
       */
      boolean hasDestinationId();
      /**
       * <code>required int32 destination_id = 3;</code>
       */
      int getDestinationId();

      // required double value = 4;
      /**
       * <code>required double value = 4;</code>
       */
      boolean hasValue();
      /**
       * <code>required double value = 4;</code>
       */
      double getValue();
    }
    /**
     * Protobuf type {@code edu.washington.escience.myria.proto.Vertex.Edge}
     */
    public static final class Edge extends
        com.google.protobuf.GeneratedMessage
        implements EdgeOrBuilder {
      // Use Edge.newBuilder() to construct.
      private Edge(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Edge(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Edge defaultInstance;
      public static Edge getDefaultInstance() {
        return defaultInstance;
      }

      public Edge getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Edge(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 24: {
                bitField0_ |= 0x00000001;
                destinationId_ = input.readInt32();
                break;
              }
              case 33: {
                bitField0_ |= 0x00000002;
                value_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertex_Edge_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertex_Edge_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.washington.escience.myria.proto.Graph.Vertex.Edge.class, edu.washington.escience.myria.proto.Graph.Vertex.Edge.Builder.class);
      }

      public static com.google.protobuf.Parser<Edge> PARSER =
          new com.google.protobuf.AbstractParser<Edge>() {
        public Edge parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Edge(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Edge> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 destination_id = 3;
      public static final int DESTINATION_ID_FIELD_NUMBER = 3;
      private int destinationId_;
      /**
       * <code>required int32 destination_id = 3;</code>
       */
      public boolean hasDestinationId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 destination_id = 3;</code>
       */
      public int getDestinationId() {
        return destinationId_;
      }

      // required double value = 4;
      public static final int VALUE_FIELD_NUMBER = 4;
      private double value_;
      /**
       * <code>required double value = 4;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double value = 4;</code>
       */
      public double getValue() {
        return value_;
      }

      private void initFields() {
        destinationId_ = 0;
        value_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasDestinationId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(3, destinationId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(4, value_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, destinationId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(4, value_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static edu.washington.escience.myria.proto.Graph.Vertex.Edge parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu.washington.escience.myria.proto.Graph.Vertex.Edge parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu.washington.escience.myria.proto.Graph.Vertex.Edge parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu.washington.escience.myria.proto.Graph.Vertex.Edge parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu.washington.escience.myria.proto.Graph.Vertex.Edge parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static edu.washington.escience.myria.proto.Graph.Vertex.Edge parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static edu.washington.escience.myria.proto.Graph.Vertex.Edge parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static edu.washington.escience.myria.proto.Graph.Vertex.Edge parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static edu.washington.escience.myria.proto.Graph.Vertex.Edge parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static edu.washington.escience.myria.proto.Graph.Vertex.Edge parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(edu.washington.escience.myria.proto.Graph.Vertex.Edge prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code edu.washington.escience.myria.proto.Vertex.Edge}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements edu.washington.escience.myria.proto.Graph.Vertex.EdgeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertex_Edge_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertex_Edge_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  edu.washington.escience.myria.proto.Graph.Vertex.Edge.class, edu.washington.escience.myria.proto.Graph.Vertex.Edge.Builder.class);
        }

        // Construct using edu.washington.escience.myria.proto.Graph.Vertex.Edge.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          destinationId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertex_Edge_descriptor;
        }

        public edu.washington.escience.myria.proto.Graph.Vertex.Edge getDefaultInstanceForType() {
          return edu.washington.escience.myria.proto.Graph.Vertex.Edge.getDefaultInstance();
        }

        public edu.washington.escience.myria.proto.Graph.Vertex.Edge build() {
          edu.washington.escience.myria.proto.Graph.Vertex.Edge result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public edu.washington.escience.myria.proto.Graph.Vertex.Edge buildPartial() {
          edu.washington.escience.myria.proto.Graph.Vertex.Edge result = new edu.washington.escience.myria.proto.Graph.Vertex.Edge(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.destinationId_ = destinationId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof edu.washington.escience.myria.proto.Graph.Vertex.Edge) {
            return mergeFrom((edu.washington.escience.myria.proto.Graph.Vertex.Edge)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(edu.washington.escience.myria.proto.Graph.Vertex.Edge other) {
          if (other == edu.washington.escience.myria.proto.Graph.Vertex.Edge.getDefaultInstance()) return this;
          if (other.hasDestinationId()) {
            setDestinationId(other.getDestinationId());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasDestinationId()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          edu.washington.escience.myria.proto.Graph.Vertex.Edge parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (edu.washington.escience.myria.proto.Graph.Vertex.Edge) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 destination_id = 3;
        private int destinationId_ ;
        /**
         * <code>required int32 destination_id = 3;</code>
         */
        public boolean hasDestinationId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 destination_id = 3;</code>
         */
        public int getDestinationId() {
          return destinationId_;
        }
        /**
         * <code>required int32 destination_id = 3;</code>
         */
        public Builder setDestinationId(int value) {
          bitField0_ |= 0x00000001;
          destinationId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 destination_id = 3;</code>
         */
        public Builder clearDestinationId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          destinationId_ = 0;
          onChanged();
          return this;
        }

        // required double value = 4;
        private double value_ ;
        /**
         * <code>required double value = 4;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required double value = 4;</code>
         */
        public double getValue() {
          return value_;
        }
        /**
         * <code>required double value = 4;</code>
         */
        public Builder setValue(double value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double value = 4;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:edu.washington.escience.myria.proto.Vertex.Edge)
      }

      static {
        defaultInstance = new Edge(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:edu.washington.escience.myria.proto.Vertex.Edge)
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required double value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private double value_;
    /**
     * <code>required double value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double value = 2;</code>
     */
    public double getValue() {
      return value_;
    }

    // repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;
    public static final int EDGE_FIELD_NUMBER = 5;
    private java.util.List<edu.washington.escience.myria.proto.Graph.Vertex.Edge> edge_;
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
     */
    public java.util.List<edu.washington.escience.myria.proto.Graph.Vertex.Edge> getEdgeList() {
      return edge_;
    }
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
     */
    public java.util.List<? extends edu.washington.escience.myria.proto.Graph.Vertex.EdgeOrBuilder> 
        getEdgeOrBuilderList() {
      return edge_;
    }
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
     */
    public int getEdgeCount() {
      return edge_.size();
    }
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
     */
    public edu.washington.escience.myria.proto.Graph.Vertex.Edge getEdge(int index) {
      return edge_.get(index);
    }
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
     */
    public edu.washington.escience.myria.proto.Graph.Vertex.EdgeOrBuilder getEdgeOrBuilder(
        int index) {
      return edge_.get(index);
    }

    private void initFields() {
      id_ = 0;
      value_ = 0D;
      edge_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getEdgeCount(); i++) {
        if (!getEdge(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, value_);
      }
      for (int i = 0; i < edge_.size(); i++) {
        output.writeMessage(5, edge_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, value_);
      }
      for (int i = 0; i < edge_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, edge_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.washington.escience.myria.proto.Graph.Vertex parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertex parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertex parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertex parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertex parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertex parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertex parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertex parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertex parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertex parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.washington.escience.myria.proto.Graph.Vertex prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.washington.escience.myria.proto.Vertex}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.washington.escience.myria.proto.Graph.VertexOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertex_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertex_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.washington.escience.myria.proto.Graph.Vertex.class, edu.washington.escience.myria.proto.Graph.Vertex.Builder.class);
      }

      // Construct using edu.washington.escience.myria.proto.Graph.Vertex.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEdgeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (edgeBuilder_ == null) {
          edge_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          edgeBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertex_descriptor;
      }

      public edu.washington.escience.myria.proto.Graph.Vertex getDefaultInstanceForType() {
        return edu.washington.escience.myria.proto.Graph.Vertex.getDefaultInstance();
      }

      public edu.washington.escience.myria.proto.Graph.Vertex build() {
        edu.washington.escience.myria.proto.Graph.Vertex result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.washington.escience.myria.proto.Graph.Vertex buildPartial() {
        edu.washington.escience.myria.proto.Graph.Vertex result = new edu.washington.escience.myria.proto.Graph.Vertex(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        if (edgeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            edge_ = java.util.Collections.unmodifiableList(edge_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.edge_ = edge_;
        } else {
          result.edge_ = edgeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.washington.escience.myria.proto.Graph.Vertex) {
          return mergeFrom((edu.washington.escience.myria.proto.Graph.Vertex)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.washington.escience.myria.proto.Graph.Vertex other) {
        if (other == edu.washington.escience.myria.proto.Graph.Vertex.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (edgeBuilder_ == null) {
          if (!other.edge_.isEmpty()) {
            if (edge_.isEmpty()) {
              edge_ = other.edge_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureEdgeIsMutable();
              edge_.addAll(other.edge_);
            }
            onChanged();
          }
        } else {
          if (!other.edge_.isEmpty()) {
            if (edgeBuilder_.isEmpty()) {
              edgeBuilder_.dispose();
              edgeBuilder_ = null;
              edge_ = other.edge_;
              bitField0_ = (bitField0_ & ~0x00000004);
              edgeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEdgeFieldBuilder() : null;
            } else {
              edgeBuilder_.addAllMessages(other.edge_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        for (int i = 0; i < getEdgeCount(); i++) {
          if (!getEdge(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.washington.escience.myria.proto.Graph.Vertex parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.washington.escience.myria.proto.Graph.Vertex) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required double value = 2;
      private double value_ ;
      /**
       * <code>required double value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double value = 2;</code>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>required double value = 2;</code>
       */
      public Builder setValue(double value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0D;
        onChanged();
        return this;
      }

      // repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;
      private java.util.List<edu.washington.escience.myria.proto.Graph.Vertex.Edge> edge_ =
        java.util.Collections.emptyList();
      private void ensureEdgeIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          edge_ = new java.util.ArrayList<edu.washington.escience.myria.proto.Graph.Vertex.Edge>(edge_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          edu.washington.escience.myria.proto.Graph.Vertex.Edge, edu.washington.escience.myria.proto.Graph.Vertex.Edge.Builder, edu.washington.escience.myria.proto.Graph.Vertex.EdgeOrBuilder> edgeBuilder_;

      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public java.util.List<edu.washington.escience.myria.proto.Graph.Vertex.Edge> getEdgeList() {
        if (edgeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(edge_);
        } else {
          return edgeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public int getEdgeCount() {
        if (edgeBuilder_ == null) {
          return edge_.size();
        } else {
          return edgeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public edu.washington.escience.myria.proto.Graph.Vertex.Edge getEdge(int index) {
        if (edgeBuilder_ == null) {
          return edge_.get(index);
        } else {
          return edgeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public Builder setEdge(
          int index, edu.washington.escience.myria.proto.Graph.Vertex.Edge value) {
        if (edgeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgeIsMutable();
          edge_.set(index, value);
          onChanged();
        } else {
          edgeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public Builder setEdge(
          int index, edu.washington.escience.myria.proto.Graph.Vertex.Edge.Builder builderForValue) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          edge_.set(index, builderForValue.build());
          onChanged();
        } else {
          edgeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public Builder addEdge(edu.washington.escience.myria.proto.Graph.Vertex.Edge value) {
        if (edgeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgeIsMutable();
          edge_.add(value);
          onChanged();
        } else {
          edgeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public Builder addEdge(
          int index, edu.washington.escience.myria.proto.Graph.Vertex.Edge value) {
        if (edgeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgeIsMutable();
          edge_.add(index, value);
          onChanged();
        } else {
          edgeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public Builder addEdge(
          edu.washington.escience.myria.proto.Graph.Vertex.Edge.Builder builderForValue) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          edge_.add(builderForValue.build());
          onChanged();
        } else {
          edgeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public Builder addEdge(
          int index, edu.washington.escience.myria.proto.Graph.Vertex.Edge.Builder builderForValue) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          edge_.add(index, builderForValue.build());
          onChanged();
        } else {
          edgeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public Builder addAllEdge(
          java.lang.Iterable<? extends edu.washington.escience.myria.proto.Graph.Vertex.Edge> values) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          super.addAll(values, edge_);
          onChanged();
        } else {
          edgeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public Builder clearEdge() {
        if (edgeBuilder_ == null) {
          edge_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          edgeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public Builder removeEdge(int index) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          edge_.remove(index);
          onChanged();
        } else {
          edgeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public edu.washington.escience.myria.proto.Graph.Vertex.Edge.Builder getEdgeBuilder(
          int index) {
        return getEdgeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public edu.washington.escience.myria.proto.Graph.Vertex.EdgeOrBuilder getEdgeOrBuilder(
          int index) {
        if (edgeBuilder_ == null) {
          return edge_.get(index);  } else {
          return edgeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public java.util.List<? extends edu.washington.escience.myria.proto.Graph.Vertex.EdgeOrBuilder> 
           getEdgeOrBuilderList() {
        if (edgeBuilder_ != null) {
          return edgeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(edge_);
        }
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public edu.washington.escience.myria.proto.Graph.Vertex.Edge.Builder addEdgeBuilder() {
        return getEdgeFieldBuilder().addBuilder(
            edu.washington.escience.myria.proto.Graph.Vertex.Edge.getDefaultInstance());
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public edu.washington.escience.myria.proto.Graph.Vertex.Edge.Builder addEdgeBuilder(
          int index) {
        return getEdgeFieldBuilder().addBuilder(
            index, edu.washington.escience.myria.proto.Graph.Vertex.Edge.getDefaultInstance());
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex.Edge edge = 5;</code>
       */
      public java.util.List<edu.washington.escience.myria.proto.Graph.Vertex.Edge.Builder> 
           getEdgeBuilderList() {
        return getEdgeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.washington.escience.myria.proto.Graph.Vertex.Edge, edu.washington.escience.myria.proto.Graph.Vertex.Edge.Builder, edu.washington.escience.myria.proto.Graph.Vertex.EdgeOrBuilder> 
          getEdgeFieldBuilder() {
        if (edgeBuilder_ == null) {
          edgeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.washington.escience.myria.proto.Graph.Vertex.Edge, edu.washington.escience.myria.proto.Graph.Vertex.Edge.Builder, edu.washington.escience.myria.proto.Graph.Vertex.EdgeOrBuilder>(
                  edge_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          edge_ = null;
        }
        return edgeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:edu.washington.escience.myria.proto.Vertex)
    }

    static {
      defaultInstance = new Vertex(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:edu.washington.escience.myria.proto.Vertex)
  }

  public interface VerticesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
     */
    java.util.List<edu.washington.escience.myria.proto.Graph.Vertex> 
        getVerticesList();
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
     */
    edu.washington.escience.myria.proto.Graph.Vertex getVertices(int index);
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
     */
    int getVerticesCount();
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
     */
    java.util.List<? extends edu.washington.escience.myria.proto.Graph.VertexOrBuilder> 
        getVerticesOrBuilderList();
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
     */
    edu.washington.escience.myria.proto.Graph.VertexOrBuilder getVerticesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code edu.washington.escience.myria.proto.Vertices}
   */
  public static final class Vertices extends
      com.google.protobuf.GeneratedMessage
      implements VerticesOrBuilder {
    // Use Vertices.newBuilder() to construct.
    private Vertices(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Vertices(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Vertices defaultInstance;
    public static Vertices getDefaultInstance() {
      return defaultInstance;
    }

    public Vertices getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Vertices(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                vertices_ = new java.util.ArrayList<edu.washington.escience.myria.proto.Graph.Vertex>();
                mutable_bitField0_ |= 0x00000001;
              }
              vertices_.add(input.readMessage(edu.washington.escience.myria.proto.Graph.Vertex.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          vertices_ = java.util.Collections.unmodifiableList(vertices_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertices_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertices_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.washington.escience.myria.proto.Graph.Vertices.class, edu.washington.escience.myria.proto.Graph.Vertices.Builder.class);
    }

    public static com.google.protobuf.Parser<Vertices> PARSER =
        new com.google.protobuf.AbstractParser<Vertices>() {
      public Vertices parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vertices(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Vertices> getParserForType() {
      return PARSER;
    }

    // repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;
    public static final int VERTICES_FIELD_NUMBER = 6;
    private java.util.List<edu.washington.escience.myria.proto.Graph.Vertex> vertices_;
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
     */
    public java.util.List<edu.washington.escience.myria.proto.Graph.Vertex> getVerticesList() {
      return vertices_;
    }
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
     */
    public java.util.List<? extends edu.washington.escience.myria.proto.Graph.VertexOrBuilder> 
        getVerticesOrBuilderList() {
      return vertices_;
    }
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
     */
    public int getVerticesCount() {
      return vertices_.size();
    }
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
     */
    public edu.washington.escience.myria.proto.Graph.Vertex getVertices(int index) {
      return vertices_.get(index);
    }
    /**
     * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
     */
    public edu.washington.escience.myria.proto.Graph.VertexOrBuilder getVerticesOrBuilder(
        int index) {
      return vertices_.get(index);
    }

    private void initFields() {
      vertices_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getVerticesCount(); i++) {
        if (!getVertices(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < vertices_.size(); i++) {
        output.writeMessage(6, vertices_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < vertices_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, vertices_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.washington.escience.myria.proto.Graph.Vertices parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertices parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertices parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertices parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertices parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertices parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertices parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertices parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertices parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.washington.escience.myria.proto.Graph.Vertices parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.washington.escience.myria.proto.Graph.Vertices prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.washington.escience.myria.proto.Vertices}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.washington.escience.myria.proto.Graph.VerticesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertices_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertices_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.washington.escience.myria.proto.Graph.Vertices.class, edu.washington.escience.myria.proto.Graph.Vertices.Builder.class);
      }

      // Construct using edu.washington.escience.myria.proto.Graph.Vertices.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getVerticesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (verticesBuilder_ == null) {
          vertices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          verticesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.washington.escience.myria.proto.Graph.internal_static_edu_washington_escience_myria_proto_Vertices_descriptor;
      }

      public edu.washington.escience.myria.proto.Graph.Vertices getDefaultInstanceForType() {
        return edu.washington.escience.myria.proto.Graph.Vertices.getDefaultInstance();
      }

      public edu.washington.escience.myria.proto.Graph.Vertices build() {
        edu.washington.escience.myria.proto.Graph.Vertices result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.washington.escience.myria.proto.Graph.Vertices buildPartial() {
        edu.washington.escience.myria.proto.Graph.Vertices result = new edu.washington.escience.myria.proto.Graph.Vertices(this);
        int from_bitField0_ = bitField0_;
        if (verticesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            vertices_ = java.util.Collections.unmodifiableList(vertices_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.vertices_ = vertices_;
        } else {
          result.vertices_ = verticesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.washington.escience.myria.proto.Graph.Vertices) {
          return mergeFrom((edu.washington.escience.myria.proto.Graph.Vertices)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.washington.escience.myria.proto.Graph.Vertices other) {
        if (other == edu.washington.escience.myria.proto.Graph.Vertices.getDefaultInstance()) return this;
        if (verticesBuilder_ == null) {
          if (!other.vertices_.isEmpty()) {
            if (vertices_.isEmpty()) {
              vertices_ = other.vertices_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureVerticesIsMutable();
              vertices_.addAll(other.vertices_);
            }
            onChanged();
          }
        } else {
          if (!other.vertices_.isEmpty()) {
            if (verticesBuilder_.isEmpty()) {
              verticesBuilder_.dispose();
              verticesBuilder_ = null;
              vertices_ = other.vertices_;
              bitField0_ = (bitField0_ & ~0x00000001);
              verticesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getVerticesFieldBuilder() : null;
            } else {
              verticesBuilder_.addAllMessages(other.vertices_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getVerticesCount(); i++) {
          if (!getVertices(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.washington.escience.myria.proto.Graph.Vertices parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.washington.escience.myria.proto.Graph.Vertices) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;
      private java.util.List<edu.washington.escience.myria.proto.Graph.Vertex> vertices_ =
        java.util.Collections.emptyList();
      private void ensureVerticesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          vertices_ = new java.util.ArrayList<edu.washington.escience.myria.proto.Graph.Vertex>(vertices_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          edu.washington.escience.myria.proto.Graph.Vertex, edu.washington.escience.myria.proto.Graph.Vertex.Builder, edu.washington.escience.myria.proto.Graph.VertexOrBuilder> verticesBuilder_;

      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public java.util.List<edu.washington.escience.myria.proto.Graph.Vertex> getVerticesList() {
        if (verticesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vertices_);
        } else {
          return verticesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public int getVerticesCount() {
        if (verticesBuilder_ == null) {
          return vertices_.size();
        } else {
          return verticesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public edu.washington.escience.myria.proto.Graph.Vertex getVertices(int index) {
        if (verticesBuilder_ == null) {
          return vertices_.get(index);
        } else {
          return verticesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public Builder setVertices(
          int index, edu.washington.escience.myria.proto.Graph.Vertex value) {
        if (verticesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVerticesIsMutable();
          vertices_.set(index, value);
          onChanged();
        } else {
          verticesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public Builder setVertices(
          int index, edu.washington.escience.myria.proto.Graph.Vertex.Builder builderForValue) {
        if (verticesBuilder_ == null) {
          ensureVerticesIsMutable();
          vertices_.set(index, builderForValue.build());
          onChanged();
        } else {
          verticesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public Builder addVertices(edu.washington.escience.myria.proto.Graph.Vertex value) {
        if (verticesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVerticesIsMutable();
          vertices_.add(value);
          onChanged();
        } else {
          verticesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public Builder addVertices(
          int index, edu.washington.escience.myria.proto.Graph.Vertex value) {
        if (verticesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVerticesIsMutable();
          vertices_.add(index, value);
          onChanged();
        } else {
          verticesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public Builder addVertices(
          edu.washington.escience.myria.proto.Graph.Vertex.Builder builderForValue) {
        if (verticesBuilder_ == null) {
          ensureVerticesIsMutable();
          vertices_.add(builderForValue.build());
          onChanged();
        } else {
          verticesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public Builder addVertices(
          int index, edu.washington.escience.myria.proto.Graph.Vertex.Builder builderForValue) {
        if (verticesBuilder_ == null) {
          ensureVerticesIsMutable();
          vertices_.add(index, builderForValue.build());
          onChanged();
        } else {
          verticesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public Builder addAllVertices(
          java.lang.Iterable<? extends edu.washington.escience.myria.proto.Graph.Vertex> values) {
        if (verticesBuilder_ == null) {
          ensureVerticesIsMutable();
          super.addAll(values, vertices_);
          onChanged();
        } else {
          verticesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public Builder clearVertices() {
        if (verticesBuilder_ == null) {
          vertices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          verticesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public Builder removeVertices(int index) {
        if (verticesBuilder_ == null) {
          ensureVerticesIsMutable();
          vertices_.remove(index);
          onChanged();
        } else {
          verticesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public edu.washington.escience.myria.proto.Graph.Vertex.Builder getVerticesBuilder(
          int index) {
        return getVerticesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public edu.washington.escience.myria.proto.Graph.VertexOrBuilder getVerticesOrBuilder(
          int index) {
        if (verticesBuilder_ == null) {
          return vertices_.get(index);  } else {
          return verticesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public java.util.List<? extends edu.washington.escience.myria.proto.Graph.VertexOrBuilder> 
           getVerticesOrBuilderList() {
        if (verticesBuilder_ != null) {
          return verticesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vertices_);
        }
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public edu.washington.escience.myria.proto.Graph.Vertex.Builder addVerticesBuilder() {
        return getVerticesFieldBuilder().addBuilder(
            edu.washington.escience.myria.proto.Graph.Vertex.getDefaultInstance());
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public edu.washington.escience.myria.proto.Graph.Vertex.Builder addVerticesBuilder(
          int index) {
        return getVerticesFieldBuilder().addBuilder(
            index, edu.washington.escience.myria.proto.Graph.Vertex.getDefaultInstance());
      }
      /**
       * <code>repeated .edu.washington.escience.myria.proto.Vertex vertices = 6;</code>
       */
      public java.util.List<edu.washington.escience.myria.proto.Graph.Vertex.Builder> 
           getVerticesBuilderList() {
        return getVerticesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.washington.escience.myria.proto.Graph.Vertex, edu.washington.escience.myria.proto.Graph.Vertex.Builder, edu.washington.escience.myria.proto.Graph.VertexOrBuilder> 
          getVerticesFieldBuilder() {
        if (verticesBuilder_ == null) {
          verticesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.washington.escience.myria.proto.Graph.Vertex, edu.washington.escience.myria.proto.Graph.Vertex.Builder, edu.washington.escience.myria.proto.Graph.VertexOrBuilder>(
                  vertices_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          vertices_ = null;
        }
        return verticesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:edu.washington.escience.myria.proto.Vertices)
    }

    static {
      defaultInstance = new Vertices(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:edu.washington.escience.myria.proto.Vertices)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_washington_escience_myria_proto_Vertex_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_washington_escience_myria_proto_Vertex_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_washington_escience_myria_proto_Vertex_Edge_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_washington_escience_myria_proto_Vertex_Edge_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_washington_escience_myria_proto_Vertices_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_washington_escience_myria_proto_Vertices_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014export.proto\022#edu.washington.escience." +
      "myria.proto\"\222\001\n\006Vertex\022\n\n\002id\030\001 \002(\005\022\r\n\005va" +
      "lue\030\002 \002(\001\022>\n\004edge\030\005 \003(\01320.edu.washington" +
      ".escience.myria.proto.Vertex.Edge\032-\n\004Edg" +
      "e\022\026\n\016destination_id\030\003 \002(\005\022\r\n\005value\030\004 \002(\001" +
      "\"I\n\010Vertices\022=\n\010vertices\030\006 \003(\0132+.edu.was" +
      "hington.escience.myria.proto.VertexB\007B\005G" +
      "raph"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_washington_escience_myria_proto_Vertex_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_washington_escience_myria_proto_Vertex_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_washington_escience_myria_proto_Vertex_descriptor,
              new java.lang.String[] { "Id", "Value", "Edge", });
          internal_static_edu_washington_escience_myria_proto_Vertex_Edge_descriptor =
            internal_static_edu_washington_escience_myria_proto_Vertex_descriptor.getNestedTypes().get(0);
          internal_static_edu_washington_escience_myria_proto_Vertex_Edge_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_washington_escience_myria_proto_Vertex_Edge_descriptor,
              new java.lang.String[] { "DestinationId", "Value", });
          internal_static_edu_washington_escience_myria_proto_Vertices_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_edu_washington_escience_myria_proto_Vertices_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_washington_escience_myria_proto_Vertices_descriptor,
              new java.lang.String[] { "Vertices", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
