// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main.proto

package edu.washington.escience.myria.proto;

public final class TransportProto {
  private TransportProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TransportMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransportMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .TransportMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .TransportMessage.Type type = 1;</code>
     */
    edu.washington.escience.myria.proto.TransportProto.TransportMessage.Type getType();

    /**
     * <code>optional .DataMessage dataMessage = 2;</code>
     */
    boolean hasDataMessage();
    /**
     * <code>optional .DataMessage dataMessage = 2;</code>
     */
    edu.washington.escience.myria.proto.DataProto.DataMessage getDataMessage();
    /**
     * <code>optional .DataMessage dataMessage = 2;</code>
     */
    edu.washington.escience.myria.proto.DataProto.DataMessageOrBuilder getDataMessageOrBuilder();

    /**
     * <code>optional .QueryMessage queryMessage = 3;</code>
     */
    boolean hasQueryMessage();
    /**
     * <code>optional .QueryMessage queryMessage = 3;</code>
     */
    edu.washington.escience.myria.proto.QueryProto.QueryMessage getQueryMessage();
    /**
     * <code>optional .QueryMessage queryMessage = 3;</code>
     */
    edu.washington.escience.myria.proto.QueryProto.QueryMessageOrBuilder getQueryMessageOrBuilder();

    /**
     * <code>optional .ControlMessage controlMessage = 4;</code>
     */
    boolean hasControlMessage();
    /**
     * <code>optional .ControlMessage controlMessage = 4;</code>
     */
    edu.washington.escience.myria.proto.ControlProto.ControlMessage getControlMessage();
    /**
     * <code>optional .ControlMessage controlMessage = 4;</code>
     */
    edu.washington.escience.myria.proto.ControlProto.ControlMessageOrBuilder getControlMessageOrBuilder();
  }
  /**
   * Protobuf type {@code TransportMessage}
   */
  public static final class TransportMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TransportMessage)
      TransportMessageOrBuilder {
    // Use TransportMessage.newBuilder() to construct.
    private TransportMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TransportMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TransportMessage defaultInstance;
    public static TransportMessage getDefaultInstance() {
      return defaultInstance;
    }

    public TransportMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TransportMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.washington.escience.myria.proto.TransportProto.TransportMessage.Type value = edu.washington.escience.myria.proto.TransportProto.TransportMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              edu.washington.escience.myria.proto.DataProto.DataMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = dataMessage_.toBuilder();
              }
              dataMessage_ = input.readMessage(edu.washington.escience.myria.proto.DataProto.DataMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dataMessage_);
                dataMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              edu.washington.escience.myria.proto.QueryProto.QueryMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = queryMessage_.toBuilder();
              }
              queryMessage_ = input.readMessage(edu.washington.escience.myria.proto.QueryProto.QueryMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(queryMessage_);
                queryMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              edu.washington.escience.myria.proto.ControlProto.ControlMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = controlMessage_.toBuilder();
              }
              controlMessage_ = input.readMessage(edu.washington.escience.myria.proto.ControlProto.ControlMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(controlMessage_);
                controlMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.washington.escience.myria.proto.TransportProto.internal_static_TransportMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.washington.escience.myria.proto.TransportProto.internal_static_TransportMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.washington.escience.myria.proto.TransportProto.TransportMessage.class, edu.washington.escience.myria.proto.TransportProto.TransportMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<TransportMessage> PARSER =
        new com.google.protobuf.AbstractParser<TransportMessage>() {
      public TransportMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransportMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TransportMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code TransportMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DATA = 0;</code>
       */
      DATA(0, 0),
      /**
       * <code>QUERY = 1;</code>
       */
      QUERY(1, 1),
      /**
       * <code>CONTROL = 2;</code>
       */
      CONTROL(2, 2),
      ;

      /**
       * <code>DATA = 0;</code>
       */
      public static final int DATA_VALUE = 0;
      /**
       * <code>QUERY = 1;</code>
       */
      public static final int QUERY_VALUE = 1;
      /**
       * <code>CONTROL = 2;</code>
       */
      public static final int CONTROL_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return DATA;
          case 1: return QUERY;
          case 2: return CONTROL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.washington.escience.myria.proto.TransportProto.TransportMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:TransportMessage.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private edu.washington.escience.myria.proto.TransportProto.TransportMessage.Type type_;
    /**
     * <code>required .TransportMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .TransportMessage.Type type = 1;</code>
     */
    public edu.washington.escience.myria.proto.TransportProto.TransportMessage.Type getType() {
      return type_;
    }

    public static final int DATAMESSAGE_FIELD_NUMBER = 2;
    private edu.washington.escience.myria.proto.DataProto.DataMessage dataMessage_;
    /**
     * <code>optional .DataMessage dataMessage = 2;</code>
     */
    public boolean hasDataMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .DataMessage dataMessage = 2;</code>
     */
    public edu.washington.escience.myria.proto.DataProto.DataMessage getDataMessage() {
      return dataMessage_;
    }
    /**
     * <code>optional .DataMessage dataMessage = 2;</code>
     */
    public edu.washington.escience.myria.proto.DataProto.DataMessageOrBuilder getDataMessageOrBuilder() {
      return dataMessage_;
    }

    public static final int QUERYMESSAGE_FIELD_NUMBER = 3;
    private edu.washington.escience.myria.proto.QueryProto.QueryMessage queryMessage_;
    /**
     * <code>optional .QueryMessage queryMessage = 3;</code>
     */
    public boolean hasQueryMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .QueryMessage queryMessage = 3;</code>
     */
    public edu.washington.escience.myria.proto.QueryProto.QueryMessage getQueryMessage() {
      return queryMessage_;
    }
    /**
     * <code>optional .QueryMessage queryMessage = 3;</code>
     */
    public edu.washington.escience.myria.proto.QueryProto.QueryMessageOrBuilder getQueryMessageOrBuilder() {
      return queryMessage_;
    }

    public static final int CONTROLMESSAGE_FIELD_NUMBER = 4;
    private edu.washington.escience.myria.proto.ControlProto.ControlMessage controlMessage_;
    /**
     * <code>optional .ControlMessage controlMessage = 4;</code>
     */
    public boolean hasControlMessage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .ControlMessage controlMessage = 4;</code>
     */
    public edu.washington.escience.myria.proto.ControlProto.ControlMessage getControlMessage() {
      return controlMessage_;
    }
    /**
     * <code>optional .ControlMessage controlMessage = 4;</code>
     */
    public edu.washington.escience.myria.proto.ControlProto.ControlMessageOrBuilder getControlMessageOrBuilder() {
      return controlMessage_;
    }

    private void initFields() {
      type_ = edu.washington.escience.myria.proto.TransportProto.TransportMessage.Type.DATA;
      dataMessage_ = edu.washington.escience.myria.proto.DataProto.DataMessage.getDefaultInstance();
      queryMessage_ = edu.washington.escience.myria.proto.QueryProto.QueryMessage.getDefaultInstance();
      controlMessage_ = edu.washington.escience.myria.proto.ControlProto.ControlMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasDataMessage()) {
        if (!getDataMessage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasQueryMessage()) {
        if (!getQueryMessage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasControlMessage()) {
        if (!getControlMessage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, dataMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, queryMessage_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, controlMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, dataMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, queryMessage_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, controlMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.washington.escience.myria.proto.TransportProto.TransportMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.washington.escience.myria.proto.TransportProto.TransportMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.washington.escience.myria.proto.TransportProto.TransportMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.washington.escience.myria.proto.TransportProto.TransportMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.washington.escience.myria.proto.TransportProto.TransportMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.washington.escience.myria.proto.TransportProto.TransportMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.washington.escience.myria.proto.TransportProto.TransportMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.washington.escience.myria.proto.TransportProto.TransportMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.washington.escience.myria.proto.TransportProto.TransportMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.washington.escience.myria.proto.TransportProto.TransportMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.washington.escience.myria.proto.TransportProto.TransportMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransportMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransportMessage)
        edu.washington.escience.myria.proto.TransportProto.TransportMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.washington.escience.myria.proto.TransportProto.internal_static_TransportMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.washington.escience.myria.proto.TransportProto.internal_static_TransportMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.washington.escience.myria.proto.TransportProto.TransportMessage.class, edu.washington.escience.myria.proto.TransportProto.TransportMessage.Builder.class);
      }

      // Construct using edu.washington.escience.myria.proto.TransportProto.TransportMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataMessageFieldBuilder();
          getQueryMessageFieldBuilder();
          getControlMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = edu.washington.escience.myria.proto.TransportProto.TransportMessage.Type.DATA;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (dataMessageBuilder_ == null) {
          dataMessage_ = edu.washington.escience.myria.proto.DataProto.DataMessage.getDefaultInstance();
        } else {
          dataMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (queryMessageBuilder_ == null) {
          queryMessage_ = edu.washington.escience.myria.proto.QueryProto.QueryMessage.getDefaultInstance();
        } else {
          queryMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (controlMessageBuilder_ == null) {
          controlMessage_ = edu.washington.escience.myria.proto.ControlProto.ControlMessage.getDefaultInstance();
        } else {
          controlMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.washington.escience.myria.proto.TransportProto.internal_static_TransportMessage_descriptor;
      }

      public edu.washington.escience.myria.proto.TransportProto.TransportMessage getDefaultInstanceForType() {
        return edu.washington.escience.myria.proto.TransportProto.TransportMessage.getDefaultInstance();
      }

      public edu.washington.escience.myria.proto.TransportProto.TransportMessage build() {
        edu.washington.escience.myria.proto.TransportProto.TransportMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.washington.escience.myria.proto.TransportProto.TransportMessage buildPartial() {
        edu.washington.escience.myria.proto.TransportProto.TransportMessage result = new edu.washington.escience.myria.proto.TransportProto.TransportMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (dataMessageBuilder_ == null) {
          result.dataMessage_ = dataMessage_;
        } else {
          result.dataMessage_ = dataMessageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (queryMessageBuilder_ == null) {
          result.queryMessage_ = queryMessage_;
        } else {
          result.queryMessage_ = queryMessageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (controlMessageBuilder_ == null) {
          result.controlMessage_ = controlMessage_;
        } else {
          result.controlMessage_ = controlMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.washington.escience.myria.proto.TransportProto.TransportMessage) {
          return mergeFrom((edu.washington.escience.myria.proto.TransportProto.TransportMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.washington.escience.myria.proto.TransportProto.TransportMessage other) {
        if (other == edu.washington.escience.myria.proto.TransportProto.TransportMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasDataMessage()) {
          mergeDataMessage(other.getDataMessage());
        }
        if (other.hasQueryMessage()) {
          mergeQueryMessage(other.getQueryMessage());
        }
        if (other.hasControlMessage()) {
          mergeControlMessage(other.getControlMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasDataMessage()) {
          if (!getDataMessage().isInitialized()) {
            
            return false;
          }
        }
        if (hasQueryMessage()) {
          if (!getQueryMessage().isInitialized()) {
            
            return false;
          }
        }
        if (hasControlMessage()) {
          if (!getControlMessage().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.washington.escience.myria.proto.TransportProto.TransportMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.washington.escience.myria.proto.TransportProto.TransportMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private edu.washington.escience.myria.proto.TransportProto.TransportMessage.Type type_ = edu.washington.escience.myria.proto.TransportProto.TransportMessage.Type.DATA;
      /**
       * <code>required .TransportMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .TransportMessage.Type type = 1;</code>
       */
      public edu.washington.escience.myria.proto.TransportProto.TransportMessage.Type getType() {
        return type_;
      }
      /**
       * <code>required .TransportMessage.Type type = 1;</code>
       */
      public Builder setType(edu.washington.escience.myria.proto.TransportProto.TransportMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .TransportMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = edu.washington.escience.myria.proto.TransportProto.TransportMessage.Type.DATA;
        onChanged();
        return this;
      }

      private edu.washington.escience.myria.proto.DataProto.DataMessage dataMessage_ = edu.washington.escience.myria.proto.DataProto.DataMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.washington.escience.myria.proto.DataProto.DataMessage, edu.washington.escience.myria.proto.DataProto.DataMessage.Builder, edu.washington.escience.myria.proto.DataProto.DataMessageOrBuilder> dataMessageBuilder_;
      /**
       * <code>optional .DataMessage dataMessage = 2;</code>
       */
      public boolean hasDataMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .DataMessage dataMessage = 2;</code>
       */
      public edu.washington.escience.myria.proto.DataProto.DataMessage getDataMessage() {
        if (dataMessageBuilder_ == null) {
          return dataMessage_;
        } else {
          return dataMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .DataMessage dataMessage = 2;</code>
       */
      public Builder setDataMessage(edu.washington.escience.myria.proto.DataProto.DataMessage value) {
        if (dataMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataMessage_ = value;
          onChanged();
        } else {
          dataMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .DataMessage dataMessage = 2;</code>
       */
      public Builder setDataMessage(
          edu.washington.escience.myria.proto.DataProto.DataMessage.Builder builderForValue) {
        if (dataMessageBuilder_ == null) {
          dataMessage_ = builderForValue.build();
          onChanged();
        } else {
          dataMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .DataMessage dataMessage = 2;</code>
       */
      public Builder mergeDataMessage(edu.washington.escience.myria.proto.DataProto.DataMessage value) {
        if (dataMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              dataMessage_ != edu.washington.escience.myria.proto.DataProto.DataMessage.getDefaultInstance()) {
            dataMessage_ =
              edu.washington.escience.myria.proto.DataProto.DataMessage.newBuilder(dataMessage_).mergeFrom(value).buildPartial();
          } else {
            dataMessage_ = value;
          }
          onChanged();
        } else {
          dataMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .DataMessage dataMessage = 2;</code>
       */
      public Builder clearDataMessage() {
        if (dataMessageBuilder_ == null) {
          dataMessage_ = edu.washington.escience.myria.proto.DataProto.DataMessage.getDefaultInstance();
          onChanged();
        } else {
          dataMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .DataMessage dataMessage = 2;</code>
       */
      public edu.washington.escience.myria.proto.DataProto.DataMessage.Builder getDataMessageBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDataMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .DataMessage dataMessage = 2;</code>
       */
      public edu.washington.escience.myria.proto.DataProto.DataMessageOrBuilder getDataMessageOrBuilder() {
        if (dataMessageBuilder_ != null) {
          return dataMessageBuilder_.getMessageOrBuilder();
        } else {
          return dataMessage_;
        }
      }
      /**
       * <code>optional .DataMessage dataMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          edu.washington.escience.myria.proto.DataProto.DataMessage, edu.washington.escience.myria.proto.DataProto.DataMessage.Builder, edu.washington.escience.myria.proto.DataProto.DataMessageOrBuilder> 
          getDataMessageFieldBuilder() {
        if (dataMessageBuilder_ == null) {
          dataMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.washington.escience.myria.proto.DataProto.DataMessage, edu.washington.escience.myria.proto.DataProto.DataMessage.Builder, edu.washington.escience.myria.proto.DataProto.DataMessageOrBuilder>(
                  getDataMessage(),
                  getParentForChildren(),
                  isClean());
          dataMessage_ = null;
        }
        return dataMessageBuilder_;
      }

      private edu.washington.escience.myria.proto.QueryProto.QueryMessage queryMessage_ = edu.washington.escience.myria.proto.QueryProto.QueryMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.washington.escience.myria.proto.QueryProto.QueryMessage, edu.washington.escience.myria.proto.QueryProto.QueryMessage.Builder, edu.washington.escience.myria.proto.QueryProto.QueryMessageOrBuilder> queryMessageBuilder_;
      /**
       * <code>optional .QueryMessage queryMessage = 3;</code>
       */
      public boolean hasQueryMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .QueryMessage queryMessage = 3;</code>
       */
      public edu.washington.escience.myria.proto.QueryProto.QueryMessage getQueryMessage() {
        if (queryMessageBuilder_ == null) {
          return queryMessage_;
        } else {
          return queryMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .QueryMessage queryMessage = 3;</code>
       */
      public Builder setQueryMessage(edu.washington.escience.myria.proto.QueryProto.QueryMessage value) {
        if (queryMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          queryMessage_ = value;
          onChanged();
        } else {
          queryMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .QueryMessage queryMessage = 3;</code>
       */
      public Builder setQueryMessage(
          edu.washington.escience.myria.proto.QueryProto.QueryMessage.Builder builderForValue) {
        if (queryMessageBuilder_ == null) {
          queryMessage_ = builderForValue.build();
          onChanged();
        } else {
          queryMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .QueryMessage queryMessage = 3;</code>
       */
      public Builder mergeQueryMessage(edu.washington.escience.myria.proto.QueryProto.QueryMessage value) {
        if (queryMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              queryMessage_ != edu.washington.escience.myria.proto.QueryProto.QueryMessage.getDefaultInstance()) {
            queryMessage_ =
              edu.washington.escience.myria.proto.QueryProto.QueryMessage.newBuilder(queryMessage_).mergeFrom(value).buildPartial();
          } else {
            queryMessage_ = value;
          }
          onChanged();
        } else {
          queryMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .QueryMessage queryMessage = 3;</code>
       */
      public Builder clearQueryMessage() {
        if (queryMessageBuilder_ == null) {
          queryMessage_ = edu.washington.escience.myria.proto.QueryProto.QueryMessage.getDefaultInstance();
          onChanged();
        } else {
          queryMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .QueryMessage queryMessage = 3;</code>
       */
      public edu.washington.escience.myria.proto.QueryProto.QueryMessage.Builder getQueryMessageBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getQueryMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .QueryMessage queryMessage = 3;</code>
       */
      public edu.washington.escience.myria.proto.QueryProto.QueryMessageOrBuilder getQueryMessageOrBuilder() {
        if (queryMessageBuilder_ != null) {
          return queryMessageBuilder_.getMessageOrBuilder();
        } else {
          return queryMessage_;
        }
      }
      /**
       * <code>optional .QueryMessage queryMessage = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          edu.washington.escience.myria.proto.QueryProto.QueryMessage, edu.washington.escience.myria.proto.QueryProto.QueryMessage.Builder, edu.washington.escience.myria.proto.QueryProto.QueryMessageOrBuilder> 
          getQueryMessageFieldBuilder() {
        if (queryMessageBuilder_ == null) {
          queryMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.washington.escience.myria.proto.QueryProto.QueryMessage, edu.washington.escience.myria.proto.QueryProto.QueryMessage.Builder, edu.washington.escience.myria.proto.QueryProto.QueryMessageOrBuilder>(
                  getQueryMessage(),
                  getParentForChildren(),
                  isClean());
          queryMessage_ = null;
        }
        return queryMessageBuilder_;
      }

      private edu.washington.escience.myria.proto.ControlProto.ControlMessage controlMessage_ = edu.washington.escience.myria.proto.ControlProto.ControlMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.washington.escience.myria.proto.ControlProto.ControlMessage, edu.washington.escience.myria.proto.ControlProto.ControlMessage.Builder, edu.washington.escience.myria.proto.ControlProto.ControlMessageOrBuilder> controlMessageBuilder_;
      /**
       * <code>optional .ControlMessage controlMessage = 4;</code>
       */
      public boolean hasControlMessage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .ControlMessage controlMessage = 4;</code>
       */
      public edu.washington.escience.myria.proto.ControlProto.ControlMessage getControlMessage() {
        if (controlMessageBuilder_ == null) {
          return controlMessage_;
        } else {
          return controlMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ControlMessage controlMessage = 4;</code>
       */
      public Builder setControlMessage(edu.washington.escience.myria.proto.ControlProto.ControlMessage value) {
        if (controlMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          controlMessage_ = value;
          onChanged();
        } else {
          controlMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .ControlMessage controlMessage = 4;</code>
       */
      public Builder setControlMessage(
          edu.washington.escience.myria.proto.ControlProto.ControlMessage.Builder builderForValue) {
        if (controlMessageBuilder_ == null) {
          controlMessage_ = builderForValue.build();
          onChanged();
        } else {
          controlMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .ControlMessage controlMessage = 4;</code>
       */
      public Builder mergeControlMessage(edu.washington.escience.myria.proto.ControlProto.ControlMessage value) {
        if (controlMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              controlMessage_ != edu.washington.escience.myria.proto.ControlProto.ControlMessage.getDefaultInstance()) {
            controlMessage_ =
              edu.washington.escience.myria.proto.ControlProto.ControlMessage.newBuilder(controlMessage_).mergeFrom(value).buildPartial();
          } else {
            controlMessage_ = value;
          }
          onChanged();
        } else {
          controlMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .ControlMessage controlMessage = 4;</code>
       */
      public Builder clearControlMessage() {
        if (controlMessageBuilder_ == null) {
          controlMessage_ = edu.washington.escience.myria.proto.ControlProto.ControlMessage.getDefaultInstance();
          onChanged();
        } else {
          controlMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .ControlMessage controlMessage = 4;</code>
       */
      public edu.washington.escience.myria.proto.ControlProto.ControlMessage.Builder getControlMessageBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getControlMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ControlMessage controlMessage = 4;</code>
       */
      public edu.washington.escience.myria.proto.ControlProto.ControlMessageOrBuilder getControlMessageOrBuilder() {
        if (controlMessageBuilder_ != null) {
          return controlMessageBuilder_.getMessageOrBuilder();
        } else {
          return controlMessage_;
        }
      }
      /**
       * <code>optional .ControlMessage controlMessage = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          edu.washington.escience.myria.proto.ControlProto.ControlMessage, edu.washington.escience.myria.proto.ControlProto.ControlMessage.Builder, edu.washington.escience.myria.proto.ControlProto.ControlMessageOrBuilder> 
          getControlMessageFieldBuilder() {
        if (controlMessageBuilder_ == null) {
          controlMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.washington.escience.myria.proto.ControlProto.ControlMessage, edu.washington.escience.myria.proto.ControlProto.ControlMessage.Builder, edu.washington.escience.myria.proto.ControlProto.ControlMessageOrBuilder>(
                  getControlMessage(),
                  getParentForChildren(),
                  isClean());
          controlMessage_ = null;
        }
        return controlMessageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:TransportMessage)
    }

    static {
      defaultInstance = new TransportMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TransportMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransportMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TransportMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmain.proto\032\014column.proto\032\rcontrol.prot" +
      "o\032\013query.proto\"\323\001\n\020TransportMessage\022$\n\004t" +
      "ype\030\001 \002(\0162\026.TransportMessage.Type\022!\n\013dat" +
      "aMessage\030\002 \001(\0132\014.DataMessage\022#\n\014queryMes" +
      "sage\030\003 \001(\0132\r.QueryMessage\022\'\n\016controlMess" +
      "age\030\004 \001(\0132\017.ControlMessage\"(\n\004Type\022\010\n\004DA" +
      "TA\020\000\022\t\n\005QUERY\020\001\022\013\n\007CONTROL\020\002B5\n#edu.wash" +
      "ington.escience.myria.protoB\016TransportPr" +
      "oto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          edu.washington.escience.myria.proto.DataProto.getDescriptor(),
          edu.washington.escience.myria.proto.ControlProto.getDescriptor(),
          edu.washington.escience.myria.proto.QueryProto.getDescriptor(),
        }, assigner);
    internal_static_TransportMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransportMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TransportMessage_descriptor,
        new java.lang.String[] { "Type", "DataMessage", "QueryMessage", "ControlMessage", });
    edu.washington.escience.myria.proto.DataProto.getDescriptor();
    edu.washington.escience.myria.proto.ControlProto.getDescriptor();
    edu.washington.escience.myria.proto.QueryProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
