DROP TABLE testtable;
CREATE TABLE testtable (value INTEGER, label VARCHAR(20));
INSERT INTO testtable VALUES (11, "str11");
INSERT INTO testtable VALUES (22, "str22");
INSERT INTO testtable VALUES (33, "str33");
INSERT INTO testtable VALUES (44, "str44");
INSERT INTO testtable VALUES (55, "str55");
INSERT INTO testtable VALUES (66, "str66");
INSERT INTO testtable VALUES (77, "str77");
INSERT INTO testtable VALUES (88, "str88");
INSERT INTO testtable VALUES (99, "str99");
INSERT INTO testtable VALUES (100, "str100");
INSERT INTO testtable VALUES (111, "str111");
INSERT INTO testtable VALUES (122, "str122");
INSERT INTO testtable VALUES (133, "str133");
INSERT INTO testtable VALUES (144, "str144");
INSERT INTO testtable VALUES (155, "str155");

DROP TABLE testtable2;
CREATE TABLE testtable2 (value VARCHAR(20));
