#!/bin/bash
set -e
REPO_ROOT=$(git rev-parse --show-toplevel)
if [ -n "$1" ];
then
    cp "$REPO_ROOT/myriadeploy/$1" "$REPO_ROOT/myriadeploy/deployment.cfg"
elif [ ! -f "$REPO_ROOT/myriadeploy/deployment.cfg" ]
then
    cp "$REPO_ROOT/myriadeploy/deployment.cfg.local" "$REPO_ROOT/myriadeploy/deployment.cfg"
fi
"$JAVA_HOME/bin/java" -cp "$REPO_ROOT/build/libs/myria-0.1-all.jar" edu.washington.escience.myria.daemon.MyriaDriverLauncher -runtimeClass org.apache.reef.runtime.local.client.LocalRuntimeConfiguration -configPath "$REPO_ROOT/myriadeploy" -javaLibPath "$REPO_ROOT/build/libs" -nativeLibPath "$REPO_ROOT/lib" -pythonLibPath "$REPO_ROOT/python"
